# @package _global_

alpha: ???
static_action_index: ???
optimizer_id: StaticAlpha-${alpha}
policy_id: StaticAlpha-${alpha}
optimizer:
  policy_class:
    _target_: dacboenv.policy.static.StaticParameterPolicy
    _partial_: true
  policy_kwargs:
    par_val: ${static_action_index}
