sbatch piecewise_cluster.sh 1 1
sbatch piecewise_cluster.sh 2 1
sbatch piecewise_cluster.sh 3 1
sbatch piecewise_cluster.sh 1 8
sbatch piecewise_cluster.sh 2 8
sbatch piecewise_cluster.sh 3 8
sbatch piecewise_cluster.sh 1 20
sbatch piecewise_cluster.sh 2 20
sbatch piecewise_cluster.sh 3 20